# Generated by Django 2.2 on 2019-10-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
