# Generated by Django 2.2 on 2019-10-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0002_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Not Assigned', 'Not Assigned'), ('Assigned', 'Assigned'), ('Incomplete', 'Incomplete'), ('Exempt', 'Exempt')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='type_of',
            field=models.CharField(choices=[('Repeating Weekly', 'Repeating Weekly'), ('From Pacing List', 'From Pacing List')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
