# Generated by Django 2.2 on 2019-10-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0003_auto_20191011_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_enrollment', to='mygrades.Curriculum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollment', to='mygrades.Student')),
            ],
            options={
                'unique_together': {('curriculum', 'student')},
            },
        ),
    ]
