# Generated by Django 2.2 on 2019-10-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0005_auto_20191011_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradebook',
            old_name='tracking',
            new_name='complete',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='required',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='required',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
