# Generated by Django 2.2 on 2019-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0006_auto_20191011_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='level',
            field=models.CharField(choices=[('Core', 'Core'), ('Supplemental', 'Supplemental')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
