# Generated by Django 2.2 on 2019-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0007_auto_20191014_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulledRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=5, null=True)),
                ('grade', models.CharField(max_length=10, null=True)),
                ('completed', models.CharField(max_length=20, null=True)),
                ('quiz', models.CharField(max_length=5, null=True)),
                ('attendance', models.CharField(max_length=5, null=True)),
                ('average_score', models.CharField(max_length=5, null=True)),
                ('site', models.CharField(max_length=5)),
                ('previous', models.CharField(max_length=5, null=True)),
                ('total_time', models.CharField(max_length=5, null=True)),
                ('presence', models.CharField(max_length=5, null=True)),
                ('date_taken', models.DateField()),
                ('date_pulled', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
