# Generated by Django 2.2 on 2019-11-23 14:55

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Student = apps.get_model("mygrades", "Student")
    db_alias = schema_editor.connection.alias
    Student.objects.using(db_alias).update(birthdate=None)


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0016_auto_20191122_2234'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
