# Generated by Django 2.2 on 2019-11-26 12:33

from django.db import migrations

def forwards_func(apps, schema_editor):
    GradeBook = apps.get_model("mygrades", "GradeBook")
    Enrollment = apps.get_model("mygrades", "Enrollment")
    StudentGradeBookReport = apps.get_model("mygrades", "Enrollment")
    db_alias = schema_editor.connection.alias
    gbs = GradeBook.objects.using(db_alias).all()
    ens = Enrollment.objects.using(db_alias).all()
    reps = StudentGradeBookReport.objects.using(db_alias).all()
    for gb in gbs:
        gb.academic_semester = gb.academic_semester.replace('-A','').replace('-B','')
        gb.save()
    for rep in reps:
        rep.academic_semester = rep.academic_semester.replace('-A','').replace('-B','')
        rep.save()
    for en in ens:
        en.academic_semester = en.academic_semester.replace('-A','').replace('-B','')
        en.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0017_auto_20191123_1455'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
