# Generated by Django 2.2 on 2019-12-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0019_auto_20191202_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='resource_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='resource_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submitted_resource',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
