# Generated by Django 2.2 on 2019-12-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0020_auto_20191208_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='type_of',
        ),
    ]
