# Generated by Django 2.2 on 2019-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygrades', '0021_remove_assignment_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='raw',
            field=models.TextField(blank=True),
        ),
    ]
